### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by lawrencelevy** [fardog/node-chromecast-osx-audio#3]
I received the following error when installing the package while on node 0.12:

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bindings/src/node_lame.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/chromecast-osx-audio/node_modules/webcast-osx-audio/node_modules/lame
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "chromecast-osx-audio"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
 
npm ERR! osx-audio@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osx-audio@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the osx-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls osx-audio
npm ERR! There is likely additional logging output above.
```

**Comment by joscha** [comment]
:+1: same here unfortunately, already got excited - haven't tried it locally with a node 0.10 though, yet.

**Comment by bedeoverend** [comment]
Same here, on 0.12.0, switched to 0.10.31 and it works well

**Comment by fardog** [comment]
this is a known issue on 0.12; i'll put up a note in the README and publish a patch version.

**Comment by fardog** [comment]
added in fa5ce26b8aad89d042febcfc314b389f23e20d03, but leaving this open as it may help others

**Comment by andrewvalentine** [comment]
Failing for me, getting this error:

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "chromecast-osx-audio"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! osx-audio@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osx-audio@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the osx-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls osx-audio
npm ERR! There is likely additional logging output above.

No log file created.

**Comment by fardog** [comment]
hi @andrewvalentine; if you want to use `chromecast-osx-audio`, you'll need to be on node version 0.10.x (you're on 0.12.7); there should be a warning no this effect when the install starts. Unfortunately, node 0.12 won't likely be supported soon, since it'll require a rebuild of `osx-audio` in many ways.

If you want to use chromecast-osx-audio but also need a newer version of node, you can use https://github.com/creationix/nvm to easily switch node versions.

**Comment by andrewvalentine** [comment]
Thanks for that - my mistake for not reading the documentation...

Cheers,

Andrew


On 13 July 2015 at 21:16, Nathan Wittstock <notifications@github.com> wrote:

> hi @andrewvalentine <https://github.com/andrewvalentine>; if you want to
> use chromecast-osx-audio, you'll need to be on node version 0.10.x
> (you're on 0.12.7); there should be a warning no this effect when the
> install starts. Unfortunately, node 0.12 won't likely be supported soon,
> since it'll require a rebuild of osx-audio in many ways.
>
> If you want to use chromecast-osx-audio but also need a newer version of
> node, you can use https://github.com/creationix/nvm to easily switch node
> versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fardog/node-chromecast-osx-audio/issues/3#issuecomment-121042916>
> .
>



-- 
Andrew Valentine
P: 07828 045095

**Comment by fardog** [comment]
Fixed in the latest version thanks to a patch submitted to `osx-audio` https://github.com/fardog/node-osx-audio/pull/10
